name: Supabase Keep-Alive

on:
  schedule:
    - cron: "0 3 * * *" # 8:30 AM IST
  workflow_dispatch:

jobs:
  ping-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Keep-Alive Endpoint
        run: |
          echo "Pinging: $KEEP_ALIVE_URL"
          curl -i "$KEEP_ALIVE_URL"
    env:
      KEEP_ALIVE_URL: ${{ secrets.KEEP_ALIVE_URL }}
